Repository Cavonstavant/mes_equipes, pull requests merged in 2022-06, with the labels that each got.

#95 Hotfix/exit client main loop on logout
  CMakeLists.txt
  Makefile
  client/client_net_utils/CMakeLists.txt
  client/client_net_utils/client_utils.c
  client/client_net_utils/include/client_utils.h
  client/client_net_utils/include/internals.h
  client/client_net_utils/manage_fd_sets.c
  client/client_net_utils/send_message.c
  client/client_net_utils/update_client.c
  client/src/CMakeLists.txt
  client/src/run_teams_client.c
  objects/CMakeLists.txt
  server/net_utils/include/net_utils.h
  server/src/core/CMakeLists.txt
Labels: bug

#99 6/Commande - Send
  client/src/include/teams_client.h
  client/src/run_teams_client.c
  client/src/teams_client.c
  objects/CMakeLists.txt
  objects/uuid/include/object_uuid.h
  objects/uuid/src/uuid_cmp.c
  objects/wrapper/include/object_wrapper.h
  objects/wrapper/src/uuid_find_prefix.c
  server/src/core/CMakeLists.txt
  server/src/core/auth_command.c
  server/src/core/cli_commands.c
  server/src/core/create_command.c
  server/src/core/fill_command_arguments.c
  server/src/core/include/server.h
  server/src/core/send_command.c
  server/src/core/server_run.c
  server/src/core/subscribe_command.c
  server/src/core/use_command.c
Labels: Implementing, Pull Request

#100 98/Commands - All
  objects/comment/include/object_comment.h
  objects/comment/src/comment_dump.c
  objects/message/include/object_message.h
  objects/message/src/message_dump.c
  objects/thread/include/object_thread.h
  objects/thread/src/thread_dump.c
  server/src/core/CMakeLists.txt
  server/src/core/auth_command.c
  server/src/core/call_command.c
  server/src/core/cli_commands.c
  server/src/core/compute_command.c
  server/src/core/convert_command_to_structure.c
  server/src/core/create_command.c
  server/src/core/fill_command_arguments.c
  server/src/core/help_command.c
  server/src/core/include/cli_commands.h
  server/src/core/include/rcodes.h
  server/src/core/info_command.c
  server/src/core/list_command.c
  server/src/core/send_command.c
  server/src/core/subscribe_command.c
  server/src/core/use_command.c
  server/src/core/user_list_command.c
Labels: Refactoring, Implementing, Pull Request

#103 Client/97 client parse server responses
  client/client_net_utils/include/client_utils.h
  client/client_net_utils/send_message.c
  client/src/CMakeLists.txt
  client/src/entrypoint.c
  client/src/include/teams_responses.h
  client/src/run_teams_client.c
  client/src/server_responses_callbacks/CMakeLists.txt
  client/src/server_responses_callbacks/callback_201.c
  client/src/server_responses_callbacks/callback_202.c
  client/src/server_responses_callbacks/callback_203.c
  client/src/server_responses_callbacks/callback_204.c
  client/src/server_responses_callbacks/callback_206.c
  client/src/server_responses_callbacks/callback_207.c
  client/src/server_responses_callbacks/callback_208.c
  client/src/server_responses_callbacks/callback_209.c
  client/src/server_responses_callbacks/callback_210.c
  client/src/server_responses_callbacks/callback_211.c
  client/src/server_responses_callbacks/callback_212.c
  client/src/server_responses_callbacks/callback_213.c
  client/src/server_responses_callbacks/callback_214.c
  client/src/server_responses_callbacks/callback_215.c
  client/src/server_responses_callbacks/callback_216.c
  client/src/server_responses_callbacks/callback_217.c
  client/src/server_responses_callbacks/callback_218.c
  client/src/server_responses_callbacks/callback_219.c
  client/src/server_responses_callbacks/callback_220.c
  client/src/server_responses_callbacks/callback_311.c
  client/src/server_responses_callbacks/callback_320.c
  client/src/server_responses_callbacks/callback_401.c
  objects/comment/src/comment_dump.c
  objects/comment/src/comment_setter.c
  objects/message/src/message_dump.c
  objects/message/src/message_setter.c
  objects/thread/src/thread_dump.c
  objects/thread/src/thread_setter.c
  objects/wrapper/src/pack_wrapper/pack_comment_to_json.c
  objects/wrapper/src/pack_wrapper/pack_message_to_json.c
  objects/wrapper/src/pack_wrapper/pack_thread_to_json.c
  server/src/core/compute_command.c
  server/src/core/include/rcodes.h
  server/src/core/list_command.c
  server/src/core/use_command.c
  server/src/core/user_list_command.c
  tests/unit_tests/objects/comment/objects_comment_tests.c
  tests/unit_tests/objects/message/objects_message_tests.c
  tests/unit_tests/objects/thread/objects_thread_tests.c
Labels: Refactoring, help wanted, RFC

#108 Client/process events from server
  client/src/include/teams_responses.h
  client/src/run_teams_client.c
  client/src/server_responses_callbacks/CMakeLists.txt
  client/src/server_responses_callbacks/callback_601.c
  client/src/server_responses_callbacks/callback_602.c
  client/src/server_responses_callbacks/callback_603.c
  client/src/server_responses_callbacks/callback_604.c
  client/src/server_responses_callbacks/callback_605.c
  client/src/server_responses_callbacks/callback_606.c
  client/src/server_responses_callbacks/callback_607.c
  server/src/core/CMakeLists.txt
  server/src/core/auth_command.c
  server/src/core/event_gestion.c
  server/src/core/include/rcodes.h
  server/src/core/include/server.h
  server/src/core/send_command.c
Labels: help wanted, RFC, ClientCommand

#109 Server - Implement Event
  client/src/server_responses_callbacks/callback_215.c
  client/src/server_responses_callbacks/callback_216.c
  client/src/server_responses_callbacks/callback_217.c
  client/src/server_responses_callbacks/callback_604.c
  client/src/server_responses_callbacks/callback_607.c
  objects/wrapper/src/wrapper_modification.c
  server/src/core/create_command.c
  server/src/core/event_gestion.c
  server/src/core/include/server.h
  server/src/core/use_command.c
Labels: Refactoring, Implementing, Pull Request
