Repository Cavonstavant/mes_equipes, pull requests merged in 2022-05, with the labels that each got.

#36 Workflows - configure documentation
  Doxyfile
  docs/doxygen-awesome.css
Labels: documentation

#47 Architecture/33 - 19 architecture Objects directory
  .gitignore
  CMakeLists.txt
  objects/CMakeLists.txt
  objects/includes/object_body.h
  objects/includes/object_channel.h
  objects/includes/object_comment.h
  objects/includes/object_conversation.h
  objects/includes/object_description.h
  objects/includes/object_message.h
  objects/includes/object_name.h
  objects/includes/object_status.h
  objects/includes/object_team.h
  objects/includes/object_thread.h
  objects/includes/object_user.h
  objects/includes/object_uuid.h
  objects/src/CMakeLists.txt
  objects/src/object_body.c
  objects/src/object_channel.c
  objects/src/object_comment.c
  objects/src/object_conversation.c
  objects/src/object_description.c
  objects/src/object_message.c
  objects/src/object_name.c
  objects/src/object_status.c
  objects/src/object_team.c
  objects/src/object_thread.c
  objects/src/object_user.c
  objects/src/object_uuid.c
Labels: documentation, Implementing, Pull Request

#50 Unit tests
  CMakeLists.txt
  cmake/FindCriterion.cmake
  tests/CMakeLists.txt
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/module/CMakeLists.txt
Labels: Implementing

#45 Parser - #29 split command
  server/src/parser/include/parser.h
  server/src/parser/my_str_to_word_array.c
  server/src/parser/split_command.c
  server/src/parser/split_command.h
Labels: Pull Request

#51 [+] Add uuid_wrapper library and link it to the objects
  objects/CMakeLists.txt
  objects/uuid/uuid_wrapper/CMakeLists.txt
  objects/uuid/uuid_wrapper/src/CMakeLists.txt
  objects/uuid/uuid_wrapper/src/include/my_uuid.h
  objects/uuid/uuid_wrapper/src/my_uuid.c
  objects/uuid/uuid_wrapper/src/uuid_prefixes.c
Labels: Implementing

#49 Parser - call command
  server/src/parser/CMakeLists.txt
  server/src/parser/call_command.c
  server/src/parser/check_command.c
  server/src/parser/cli_commands.c
  server/src/parser/cli_commands.h
  server/src/parser/include/parser.h
  server/src/parser/split_command.h
Labels: Pull Request

#37 Parser - #32 compute command
  server/src/parser/CMakeLists.txt
  server/src/parser/compute_command.c
  server/src/parser/include/parser.h
Labels: Pull Request

#54 Architecture/20 - Implement Complex object Init / Destructor
  .gitignore
  Makefile
  objects/CMakeLists.txt
  objects/body/include/object_body.h
  objects/channel/include/object_channel.h
  objects/channel/src/object_channel.c
  objects/comment/include/object_comment.h
  objects/comment/src/object_comment.c
  objects/conversation/include/object_conversation.h
  objects/conversation/src/object_conversation.c
  objects/description/include/object_description.h
  objects/message/include/object_message.h
  objects/message/src/object_message.c
  objects/name/include/object_name.h
  objects/team/include/object_team.h
  objects/team/src/object_team.c
  objects/thread/include/object_thread.h
  objects/thread/src/object_thread.c
  objects/user/include/object_user.h
  objects/user/src/object_user.c
  objects/uuid/include/object_uuid.h
  objects/uuid/src/object_uuid.c
  objects/uuid/uuid_wrapper/src/include/my_uuid.h
  objects/uuid/uuid_wrapper/src/my_uuid.c
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/objects/CMakeLists.txt
  tests/unit_tests/objects/body/CMakeLists.txt
  tests/unit_tests/objects/body/objects_body_tests.c
  tests/unit_tests/objects/channel/CMakeLists.txt
  tests/unit_tests/objects/channel/objects_channel_tests.c
  tests/unit_tests/objects/comment/CMakeLists.txt
  tests/unit_tests/objects/comment/objects_comment_tests.c
  tests/unit_tests/objects/conversation/CMakeLists.txt
  tests/unit_tests/objects/conversation/objects_conversation_tests.c
  tests/unit_tests/objects/description/CMakeLists.txt
  tests/unit_tests/objects/description/objects_description_tests.c
  tests/unit_tests/objects/message/CMakeLists.txt
  tests/unit_tests/objects/message/objects_message_tests.c
  tests/unit_tests/objects/name/CMakeLists.txt
  tests/unit_tests/objects/name/objects_name_tests.c
  tests/unit_tests/objects/status/CMakeLists.txt
  tests/unit_tests/objects/status/objects_status_tests.c
  tests/unit_tests/objects/team/CMakeLists.txt
  tests/unit_tests/objects/team/objects_team_tests.c
  tests/unit_tests/objects/thread/CMakeLists.txt
  tests/unit_tests/objects/thread/objects_thread_tests.c
  tests/unit_tests/objects/user/CMakeLists.txt
  tests/unit_tests/objects/user/objects_user_tests.c
  tests/unit_tests/objects/uuid/CMakeLists.txt
  tests/unit_tests/objects/uuid/objects_uuid_tests.c
  tests/unit_tests/template/module/CMakeLists.txt
Labels: documentation, Implementing, Pull Request

#55 Architecture/44 - Implement Wrapper Object #54
  objects/CMakeLists.txt
  objects/comment/include/object_comment.h
  objects/uuid/src/object_uuid.c
  objects/wrapper/include/lower_component_adding.h
  objects/wrapper/include/object_wrapper.h
  objects/wrapper/include/upper_component_adding.h
  objects/wrapper/src/lower_component_adding.c
  objects/wrapper/src/object_wrapper.c
  objects/wrapper/src/upper_component_adding.c
  tests/unit_tests/objects/CMakeLists.txt
  tests/unit_tests/objects/body/objects_body_tests.c
  tests/unit_tests/objects/channel/objects_channel_tests.c
  tests/unit_tests/objects/comment/objects_comment_tests.c
  tests/unit_tests/objects/conversation/objects_conversation_tests.c
  tests/unit_tests/objects/description/objects_description_tests.c
  tests/unit_tests/objects/message/objects_message_tests.c
  tests/unit_tests/objects/name/objects_name_tests.c
  tests/unit_tests/objects/team/objects_team_tests.c
  tests/unit_tests/objects/thread/objects_thread_tests.c
  tests/unit_tests/objects/user/objects_user_tests.c
  tests/unit_tests/objects/uuid/objects_uuid_tests.c
  tests/unit_tests/objects/wrapper/CMakeLists.txt
  tests/unit_tests/objects/wrapper/lower_component_adding_tests.c
  tests/unit_tests/objects/wrapper/objects_wrapper_tests.c
  tests/unit_tests/objects/wrapper/upper_component_adding_tests.c
Labels: documentation, Implementing, Pull Request

#63 [+] create architecture for ClientCommands part
  server/src/CMakeLists.txt
  server/src/commands/CMakeLists.txt
Labels: Implementing

#59 [*] fix called function name in compute_command function
  server/src/parser/compute_command.c
Labels: bug

#53 Network/refactoring/select/15 network refactoring select
  .github/workflows/cmake.yml
  CMakeLists.txt
  Makefile
  server/CMakeLists.txt
  server/net_utils/CMakeLists.txt
  server/net_utils/auth/CMakeLists.txt
  server/net_utils/auth/user.c
  server/net_utils/display_utils.c
  server/net_utils/fd_sets_manage/CMakeLists.txt
  server/net_utils/fd_sets_manage/fd_set_manage.h
  server/net_utils/fd_sets_manage/fd_sets_manage.c
  server/net_utils/fd_sets_manage/server_accept_new_client.c
  server/net_utils/fd_sets_manage/server_close_client.c
  server/net_utils/fd_sets_manage/server_read_client.c
  server/net_utils/fd_sets_manage/server_write_client.c
  server/net_utils/include/net_utils.h
  server/net_utils/include/net_utils/auth/user.h
  server/net_utils/peer.c
  server/net_utils/remove_unused_sockets.c
  server/net_utils/select.c
  server/net_utils/tcp_server.c
  server/src/CMakeLists.txt
Labels: Refactoring, Implementing

#71 Architecture/44 Implement Wrapper Getter
  objects/CMakeLists.txt
  objects/uuid/include/object_uuid.h
  objects/uuid/src/uuid_cmp.c
  objects/wrapper/include/object_wrapper.h
  objects/wrapper/src/lower_component_get.c
  objects/wrapper/src/upper_component_get.c
  tests/unit_tests/objects/comment/objects_comment_tests.c
  tests/unit_tests/objects/message/objects_message_tests.c
  tests/unit_tests/objects/thread/objects_thread_tests.c
  tests/unit_tests/objects/uuid/objects_uuid_tests.c
  tests/unit_tests/objects/wrapper/CMakeLists.txt
  tests/unit_tests/objects/wrapper/lower_component_get_tests.c
  tests/unit_tests/objects/wrapper/upper_component_get_tests.c
Labels: Implementing

#74 Client command/73 rfc returns codes
  server/src/commands/CMakeLists.txt
  server/src/commands/rcodes.h
Labels: Pull Request

#72 Architecture/44 Implement Wrapper Interaction
  objects/CMakeLists.txt
  objects/wrapper/include/object_wrapper.h
  objects/wrapper/src/wrapper_interaction.c
  objects/wrapper/src/wrapper_modification.c
  tests/unit_tests/objects/wrapper/CMakeLists.txt
  tests/unit_tests/objects/wrapper/wrapper_interaction_tests.c
Labels: Implementing, Pull Request

#77 76/API - Link API Library
  .gitignore
  client/src/CMakeLists.txt
  libs/libmyteams.so
  libs/logging_client.h
  libs/logging_server.h
  objects/CMakeLists.txt
  server/src/CMakeLists.txt
Labels: Implementing

#84 81/Architecture - Utilitary function
  objects/CMakeLists.txt
  objects/conversation/include/object_conversation.h
  objects/conversation/src/conversation_setter.c
  objects/wrapper/include/object_wrapper.h
  objects/wrapper/src/find_by_name.c
  objects/wrapper/src/get_associated_team.c
  objects/wrapper/src/get_child_list.c
  objects/wrapper/src/user_and_team_relation.c
  objects/wrapper/src/wrapper_interaction.c
Labels: Implementing, Pull Request

#79 Implementation/69 create server and client binaries 1/2
  .github/workflows/cmake.yml
  CMakeLists.txt
  client/CMakeLists.txt
  client/client_net_utils/CMakeLists.txt
  client/client_net_utils/client_utils.c
  client/client_net_utils/fetch_message.c
  client/client_net_utils/include/client_utils.h
  client/client_net_utils/send_message.c
  client/client_net_utils/update_server.c
  client/src/CMakeLists.txt
  client/src/entrypoint.c
  server/net_utils/CMakeLists.txt
  server/net_utils/fd_sets_manage/fd_set_manage.h
  server/net_utils/fd_sets_manage/fd_sets_manage.c
  server/net_utils/fd_sets_manage/server_close_client.c
  server/net_utils/fd_sets_manage/server_read_client.c
  server/net_utils/include/net_utils.h
  server/net_utils/peer.c
  server/net_utils/remove_unused_sockets.c
  server/net_utils/tcp_server.c
  server/src/CMakeLists.txt
  server/src/client_wrapper.c
  server/src/entrypoint.c
  server/src/include/client_wrapper.h
  server/src/include/my_teams_server.h
  server/src/my_teams_server.c
Labels: Implementing

#86 85/Architecture - Link libraries
  objects/CMakeLists.txt
  server/include/entrypoint.h
  server/include/my_teams_server.h
  server/include/server.h
  server/net_utils/CMakeLists.txt
  server/net_utils/auth/CMakeLists.txt
  server/net_utils/auth/user.c
  server/net_utils/include/net_utils.h
  server/net_utils/include/net_utils/auth/user.h
  server/net_utils/tcp_server.c
  server/src/CMakeLists.txt
  server/src/client_wrapper.c
  server/src/entrypoint.c
  server/src/include/client_wrapper.h
  server/src/include/my_teams_server.h
  server/src/my_teams_server.c
  server/src/server_data.c
  server/src/server_run.c
Labels: Implementing, Pull Request

#87 85/Architecture - Link libraries
  server/include/my_teams_server.h
  server/include/server.h
  server/src/CMakeLists.txt
  server/src/my_teams_server.c
  server/src/server_data.c
  server/src/server_run.c
Labels: Implementing, Pull Request

#68 Parser/67 rebase parser
  launch_tests.sh
  objects/CMakeLists.txt
  objects/uuid/uuid_wrapper/src/CMakeLists.txt
  server/CMakeLists.txt
  server/net_utils/CMakeLists.txt
  server/src/CMakeLists.txt
  server/src/commands/CMakeLists.txt
  server/src/commands/rcodes.h
  server/src/core/CMakeLists.txt
  server/src/core/call_command.c
  server/src/core/cli_commands.c
  server/src/core/compute_command.c
  server/src/core/convert_command_to_structure.c
  server/src/core/fill_command_arguments.c
  server/src/core/include/cli_commands.h
  server/src/core/include/entrypoint.h
  server/src/core/include/my_teams_server.h
  server/src/core/include/parser.h
  server/src/core/include/rcodes.h
  server/src/core/include/server.h
  server/src/core/my_teams_server.c
  server/src/core/server_data.c
  server/src/core/server_run.c
  server/src/parser/CMakeLists.txt
  server/src/parser/call_command.c
  server/src/parser/check_command.c
  server/src/parser/cli_commands.c
  server/src/parser/cli_commands.h
  server/src/parser/compute_command.c
  server/src/parser/my_str_to_word_array.c
  server/src/parser/split_command.c
  tests/unit_tests/CMakeLists.txt
  tests/unit_tests/core/CMakeLists.txt
  tests/unit_tests/core/compute_command_test.c
Labels: Refactoring

#88 85/Architecture - Implement Logout
  objects/uuid/include/object_uuid.h
  objects/uuid/src/uuid_setter.c
  server/src/core/CMakeLists.txt
  server/src/core/auth_command.c
  server/src/core/call_command.c
  server/src/core/cli_commands.c
  server/src/core/compute_command.c
  server/src/core/convert_command_to_structure.c
  server/src/core/create_command.c
  server/src/core/fill_command_arguments.c
  server/src/core/include/cli_commands.h
  server/src/core/include/rcodes.h
  server/src/core/include/server.h
  server/src/core/server_data.c
  server/src/core/server_run.c
  server/src/core/subscribe_command.c
  tests/unit_tests/core/compute_command_test.c
Labels: Implementing, Pull Request

#93 Implementation/69 create server and client binaries
  .github/workflows/cmake.yml
  client/client_net_utils/CMakeLists.txt
  client/client_net_utils/client_utils.c
  client/client_net_utils/fetch_message.c
  client/client_net_utils/include/client_utils.h
  client/client_net_utils/internals.h
  client/client_net_utils/manage_fd_sets.c
  client/client_net_utils/send_message.c
  client/client_net_utils/update_client.c
  client/client_net_utils/update_server.c
  client/src/CMakeLists.txt
  client/src/entrypoint.c
  client/src/include/teams_client.h
  client/src/run_teams_client.c
  client/src/stop_teams_client.c
  client/src/teams_client.c
  codecov.yml
  server/net_utils/include/net_utils.h
  server/src/core/include/rcodes.h
  server/src/entrypoint.c
Labels: Implementing, Pull Request
